apiVersion: v1
kind: Pod
metadata:
  name: kubeslack
  namespace: default
spec:
  containers:
  - image: grove/kubeslack
    imagePullPolicy: Always
    name: kubeslack
    volumeMounts:
    - name: secret-volume
      mountPath: /root
  restartPolicy: Always
  volumes:
  - name: secret-volume
    secret:
      secretName: kubeslack
